version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_users
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@postgres:5432/telegram_users?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  grpc-service:
    build:
      context: .
      dockerfile: grpc-service/Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "50051:50051"

  http-service:
    build:
      context: .
      dockerfile: http-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - grpc-service

volumes:
  postgres_data: